# Generated by Django 6.0.6 on 2026-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=10)),
                ('provider', models.CharField(max_length=10)),
                ('environment', models.CharField(max_length=10)),
                ('resource_type', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=50)),
                ('instance', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'provider', 'environment', 'resource_type', 'purpose', 'instance'), name='unique_resource_identity')],
            },
        ),
    ]
