# Generated by Django 6.0.6 on 2026-07-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for the group badge (e.g. #3b82f6)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The resource group this resource belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='naming.resourcegroup'),
        ),
    ]
