# Generated by Django 6.0.6 on 2026-07-05 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0002_resourcegroup_resource_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(help_text='The resource group this resource belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='naming.resourcegroup'),
        ),
    ]
