# Generated by Django 6.0.6 on 2026-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0003_alter_resource_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='group',
        ),
        migrations.AddField(
            model_name='resource',
            name='groups',
            field=models.ManyToManyField(help_text='The resource groups this resource belongs to (at least one).', related_name='resources', to='naming.resourcegroup'),
        ),
    ]
